[phases.setup]
nixPkgs = ['php82', 'php81Packages.composer', 'nodejs', 'python3Full']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --ignore-platform-reqs',
    'npm install',
    'python3 -m venv /app/venv',
    '/app/venv/bin/pip install --upgrade pip',
    '/app/venv/bin/pip install instaloader'
]

[phases.build]
cmds = [
    'rm -f /app/public/storage',
    'ln -sf /app/storage/app/public /app/public/storage',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'npm run build'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
