[phases.setup]
nixPkgs = ['php82', 'php81Packages.composer', 'nodejs', 'python3Full']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --ignore-platform-reqs',
    'npm install',
    'python3 -m venv /app/venv',
    '/app/venv/bin/pip install --upgrade pip',
    '/app/venv/bin/pip install instaloader'
]

[phases.build]
cmds = [
    'mkdir -p /app/storage/app/public',
    'mkdir -p /app/storage/app/instagram',
    'mkdir -p /app/storage/framework/cache',
    'mkdir -p /app/storage/framework/sessions',
    'mkdir -p /app/storage/framework/views',
    'mkdir -p /app/storage/logs',
    'mkdir -p /app/public',
    'chmod -R 775 /app/storage',
    'ln -sf /app/storage/app/public /app/public/storage',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'npm run build --verbose'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
