name: Deploy to Dokku
on: push
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.DOKKU2 }}
            - name: Push to Dokku
              run: |
                  git remote add dokku ${{ secrets.USER }}@${{ secrets.HOST }}:maya
                  git push dokku master
